togglz:
  console:
    secured: false

management:
  endpoints:
    web:
      exposure:
        include: 'togglz'

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
